server:
  port: 8081


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: micro-blog-account
  main:
    allow-bean-definition-overriding: true
  redis:
    host:
    port: 15001
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#        ip: localhost


eureka:
  client:
    register-with-eureka: false    # 是否将自己注册进eurekaServer，默认true
    fetchRegistry: false         #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      defaultZone: http://localhost:9527/eureka   #单机版
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版
  instance:
    hostname: localhost



ribbon:
  ConnectTimeout: 4000
  ReadTimeout: 6000

#下划线转驼峰
mybatis:
  configuration:
    map-underscore-to-camel-case: true



#配置日志
logging:
  #此处存放日志的路径
  config: classpath:logback-spring.xml
  #指定不同目录下的日志的级别
  level:
    #com.shimain.springboot.mapper: INFO
    root: info #root表示整个项目，也可单指定某个类（指定某个类放在logback文件指定也可以）

properties:
  #token秘钥
  tokenSecret: MIICdQIBADANBgkqhkiG9w0BAQEFAASCAl8wggJbAgEAAoGBALMDRWtDsRalb8neM0JavVw1Kww5EO/ocSNkmvufeM+eWzKZtNGqULFFoU6kOoGGWFv4sHZ+vGu5oZqi/KYVxFFT3mt7r5cWGPtFQrPJGEpMuA2RDRImh0Ot2KCICQV2uuQhTRw52N7YqSMy5cSpgekGDwH6aC7PtjLaiTsUGiEtAgMBAAECgYB7UACM4Edn2zSDcW4MAme40eNCezkAmjT9dXsRZAwbsPEPjTQyzcjiJJ32h0jKGppZWJluNuViq6/3ztiNLCdb2e5Cyuhum769Zd1MvOxemfb3EGcOg/hs9WkaWap64KPRfEI70yJ/e7/uvsyiijPsU7vw0DwNsh+UHkwnBVp13QJBAO5rJ9pfoVt43K+HvWYZXCQxJ1UBl2r1VDL9Q/ygfLq5Nu3seAOkX6GOy0OVtNlUTaMAbyuW8LRyrCbL+CE01bsCQQDANqh/g6Ie1DbxQu9MExeQMaceVfakJSOwsYCa9rusQVtcplx4fiS19q2dGojuzXKD3CQ9vyjOgTcnyAFqkkI3AkBDwK/Sntp75BzSxQBNw2cr4cwLnCgrfQwwcUigwfqwFXJGqqxwXIXQo4Of8Sszl4F4kOcGvB4rKWtCmzQoO5uBAkBn9Cek7xga/ELKsJyi1CCGR5ROf8dodv2abiVTqeVN//rdXMveDrrj/ole0h8Ep/ArCEBBdMUpChE+XpkFfhx5AkBmqR/AIPvmk8aTzh61aEtolBfVaitiPFcGn0NS33GNGtbMvJoRLgkeS0tFrOnyCgsFX1f8Ktcfw5xfIA75THFo
  #ignoreAuthPath: []
  #authPath: ['**/create*/**','**/update*/**','**/save*/**','**/delete*/**','**/migrate*/**','**/change*/**',]
  defaultUserHeader: http://static.image.qyun.nzjie.cn/micro-blog-account/default_user_header.png

  github:
    tokenUrl: https://github.com/login/oauth/access_token
    userInfoUrl: https://api.github.com/user
    clientId: 9b3e3a95ca4392cc0f33
    clientSecret:
  gitee:
    tokenUrl: https://gitee.com/oauth/token
    userInfoUrl: https://gitee.com/api/v5/user
    redirectUrl: http://localhost:63342/front/vue-blog/oauth2.html?type=gitee
    clientId: 88aafe177f4f5a653dd401e4fbb69797cf2bf55767be370285d7e95b5ae61f99
    clientSecret: