server:
  port: 16001 #服务注册中心端口号
eureka:
  instance:
    hostname: 127.0.0.1 #服务注册中心IP地址
  client:
    registerWithEureka: false #是否向服务注册中心注册自己
    fetchRegistry: false #是否检索服务
    serviceUrl: #服务注册中心的配置内容，指定服务注册中心的位置
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

#配置日志
logging:
  #此处存放日志的路径
  config: classpath:logback-spring.xml
  #指定不同目录下的日志的级别
  level:
    root: INFO #root表示整个项目，也可单指定某个类（指定某个类放在logback文件指定也可以），可通过jvm参数传入修改